### ISSUE TITLE
Mapcrafter cannot determine world seed

### ISSUE THREAD

**Issue by khepler** [miclav/mapcrafter#16]
While generating slime chunk map on recent world data, the following error is logged:
```Unable to read world seed from level.dat file for slime overlay: Unable to find tag 'RandomSeed'```

I believe the level.dat was reorganized sometime around v1.16 and the seed tag moved from `.Data.RandomSeed` to `.Data.WorldGenSettings.seed`.

**Comment by miclav** [comment]
Hello
Thanks for your participation.
The fix looks nice, and doesn't affect the rotation of lily pads. 👍
