### ISSUE TITLE
Marker fails for MC 1.20

### ISSUE THREAD

**Issue by jgeiss66** [miclav/mapcrafter#19]
The tool mapcrafter_markes fails for Minecraft 1.20 with the following error:

`terminate called after throwing an instance of 'mapcrafter::mc::nbt::TagNotFound'
  what():  Unable to find (const) tag 'Text1'
`

**Comment by doismellburning** [comment]
Looks like the sign changes - https://minecraft.fandom.com/wiki/Sign#Data_values

Before 1.20, text was in `Text1` through to 4; with 1.20 it's `front_text.messages[n]` (or `back_text`!)

**Comment by doismellburning** [comment]
Someone with more C++ ability / a better dev setup than I have should be able to take https://github.com/miclav/mapcrafter/blob/d776cee5abb6f7be37e834c7c379c87c031d6756/src/mapcraftercore/mc/worldentities.cpp#L286-L291 and replace `entity.findTag<nbt::TagString>("Text1").payload` etc. with logic to `hasTag` for `front_text` etc.

I'll try, but I'm still working on figuring out the test setup etc....

**Comment by miclav** [comment]
Thanks for looking into this issue
